
# Generated by Django 4.2.1 on 2024-05-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(max_length=200, verbose_name='Электронная почта')),
                ('question', models.TextField(max_length=800, verbose_name='Вопрос')),
            ],
        ),
    ]
