
# Generated by Django 4.2.1 on 2024-05-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('math', 'Математика'), ('history', 'История'), ('chemistry', 'Химия'), ('biology', 'Биология'), ('physics', 'Физика'), ('geography', 'География')], max_length=50)),
                ('question', models.TextField()),
                ('answer', models.BooleanField()),
            ],
        ),
    ]
